export const doctors = [
  {
    name: "Dr. Kavita Mehra",
    email: "kavita.mehra@mediconnect.in",
    password: "Doctor@123",
    image: "doc1.jpg",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "6 Years",
    about:
      "Dr. Mehra specializes in primary healthcare, lifestyle disorders, and preventive medicine with a patient-first approach.",
    fees: 450,
    address: { line1: "DLF Phase 3", line2: "Gurugram, Haryana" },
  },
  {
    name: "Dr. Nitin Aggarwal",
    email: "nitin.aggarwal@mediconnect.in",
    password: "Doctor@123",
    image: "doc2.jpg",
    speciality: "Gynecologist",
    degree: "MBBS, DGO",
    experience: "8 Years",
    about:
      "Dr. Aggarwal provides comprehensive women’s healthcare including antenatal care, infertility counseling, and gynecological procedures.",
    fees: 650,
    address: { line1: "Sector 62", line2: "Noida, Uttar Pradesh" },
  },
  {
    name: "Dr. Rohan Malviya",
    email: "rohan.malviya@mediconnect.in",
    password: "Doctor@123",
    image: "doc3.jpg",
    speciality: "Dermatologist",
    degree: "MBBS, MD (Dermatology)",
    experience: "3 Years",
    about:
      "Dr. Malviya treats skin, hair, and nail disorders using evidence-based dermatological and cosmetic treatments.",
    fees: 400,
    address: { line1: "Vijay Nagar", line2: "Indore, Madhya Pradesh" },
  },
  {
    name: "Dr. Pooja Kulkarni",
    email: "pooja.kulkarni@mediconnect.in",
    password: "Doctor@123",
    image: "doc4.jpg",
    speciality: "Pediatrician",
    degree: "MBBS, MD (Pediatrics)",
    experience: "5 Years",
    about:
      "Dr. Kulkarni focuses on child growth, immunization, and preventive pediatric care.",
    fees: 500,
    address: { line1: "Baner", line2: "Pune, Maharashtra" },
  },
  {
    name: "Dr. Arvind Iyer",
    email: "arvind.iyer@mediconnect.in",
    password: "Doctor@123",
    image: "doc5.jpg",
    speciality: "Neurologist",
    degree: "MBBS, DM (Neurology)",
    experience: "10 Years",
    about:
      "Dr. Iyer specializes in treating migraines, epilepsy, stroke, and other neurological disorders.",
    fees: 800,
    address: { line1: "Adyar", line2: "Chennai, Tamil Nadu" },
  },
  {
    name: "Dr. Sameer Qureshi",
    email: "sameer.qureshi@mediconnect.in",
    password: "Doctor@123",
    image: "doc6.jpg",
    speciality: "Gastroenterologist",
    degree: "MBBS, DM (Gastroenterology)",
    experience: "7 Years",
    about:
      "Dr. Qureshi manages digestive disorders including IBS, liver diseases, and acid reflux with a holistic approach.",
    fees: 700,
    address: { line1: "Jogeshwari East", line2: "Mumbai, Maharashtra" },
  },
  {
    name: "Dr. Ananya Sengupta",
    email: "ananya.sengupta@mediconnect.in",
    password: "Doctor@123",
    image: "doc7.jpg",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "4 Years",
    about:
      "Dr. Sengupta focuses on early diagnosis, chronic disease management, and preventive healthcare.",
    fees: 450,
    address: { line1: "Ballygunge", line2: "Kolkata, West Bengal" },
  },
  {
    name: "Dr. Mohit Saxena",
    email: "mohit.saxena@mediconnect.in",
    password: "Doctor@123",
    image: "doc8.jpg",
    speciality: "Orthopedic",
    degree: "MBBS, MS (Orthopedics)",
    experience: "6 Years",
    about:
      "Dr. Saxena treats bone, joint, and sports injuries using modern orthopedic techniques.",
    fees: 600,
    address: { line1: "Alambagh", line2: "Lucknow, Uttar Pradesh" },
  },
  {
    name: "Dr. Isha Patel",
    email: "isha.patel@mediconnect.in",
    password: "Doctor@123",
    image: "doc9.jpg",
    speciality: "Dermatologist",
    degree: "MBBS, MD (Dermatology)",
    experience: "5 Years",
    about:
      "Dr. Patel combines clinical dermatology with aesthetic procedures for comprehensive skin care.",
    fees: 500,
    address: { line1: "Satellite", line2: "Ahmedabad, Gujarat" },
  },
  {
    name: "Dr. Kunal Bhatia",
    email: "kunal.bhatia@mediconnect.in",
    password: "Doctor@123",
    image: "doc10.jpg",
    speciality: "Pediatrician",
    degree: "MBBS, MD (Pediatrics)",
    experience: "7 Years",
    about:
      "Dr. Bhatia is dedicated to pediatric wellness, nutrition, and developmental monitoring.",
    fees: 550,
    address: { line1: "Rohini", line2: "New Delhi, Delhi" },
  },
  {
    name: "Dr. Sandeep Khanna",
    email: "sandeep.khanna@mediconnect.in",
    password: "Doctor@123",
    image: "doc21.jpg",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "9 Years",
    about:
      "Dr. Khanna focuses on internal medicine, diabetes management, and preventive healthcare.",
    fees: 500,
    address: { line1: "Rajouri Garden", line2: "New Delhi, Delhi" },
  },
  {
    name: "Dr. Neelam Joshi",
    email: "neelam.joshi@mediconnect.in",
    password: "Doctor@123",
    image: "doc1.jpg",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "5 Years",
    about:
      "Dr. Joshi provides patient-centric primary care with emphasis on lifestyle disorders.",
    fees: 400,
    address: { line1: "Kothrud", line2: "Pune, Maharashtra" },
  },

  // -------- Gynecologists --------
  {
    name: "Dr. Richa Tandon",
    email: "richa.tandon@mediconnect.in",
    password: "Doctor@123",
    image: "doc2.jpg",
    speciality: "Gynecologist",
    degree: "MBBS, MS (Obstetrics & Gynecology)",
    experience: "10 Years",
    about:
      "Dr. Tandon specializes in high-risk pregnancies, prenatal care, and fertility treatment.",
    fees: 700,
    address: { line1: "Vaishali Nagar", line2: "Jaipur, Rajasthan" },
  },
  {
    name: "Dr. Farah Naaz",
    email: "farah.naaz@mediconnect.in",
    password: "Doctor@123",
    image: "doc3.jpg",
    speciality: "Gynecologist",
    degree: "MBBS, DGO",
    experience: "6 Years",
    about:
      "Dr. Naaz provides comprehensive gynecological care including menstrual and hormonal disorders.",
    fees: 600,
    address: { line1: "Charminar", line2: "Hyderabad, Telangana" },
  },

  // -------- Dermatologists --------
  {
    name: "Dr. Akshay Kuldeep",
    email: "akshay.kuldeep@mediconnect.in",
    password: "Doctor@123",
    image: "doc4.jpg",
    speciality: "Dermatologist",
    degree: "MBBS, MD (Dermatology)",
    experience: "4 Years",
    about:
      "Dr. Kuldeep treats acne, pigmentation, and hair loss using modern dermatological solutions.",
    fees: 450,
    address: { line1: "Vesu", line2: "Surat, Gujarat" },
  },
  {
    name: "Dr. Sneha Rao",
    email: "sneha.rao@mediconnect.in",
    password: "Doctor@123",
    image: "doc5.jpg",
    speciality: "Dermatologist",
    degree: "MBBS, MD (Dermatology)",
    experience: "7 Years",
    about:
      "Dr. Rao combines clinical dermatology with aesthetic skin treatments.",
    fees: 550,
    address: { line1: "Whitefield", line2: "Bengaluru, Karnataka" },
  },

  // -------- Pediatricians --------
  {
    name: "Dr. Ankit Bhowmik",
    email: "ankit.bhowmik@mediconnect.in",
    password: "Doctor@123",
    image: "doc6.jpg",
    speciality: "Pediatrician",
    degree: "MBBS, MD (Pediatrics)",
    experience: "6 Years",
    about:
      "Dr. Bhowmik focuses on child nutrition, immunization, and developmental assessment.",
    fees: 500,
    address: { line1: "Lake Town", line2: "Kolkata, West Bengal" },
  },
  {
    name: "Dr. Meenal Parikh",
    email: "meenal.parikh@mediconnect.in",
    password: "Doctor@123",
    image: "doc7.jpg",
    speciality: "Pediatrician",
    degree: "MBBS, MD (Pediatrics)",
    experience: "8 Years",
    about:
      "Dr. Parikh provides holistic pediatric care with special focus on newborn health.",
    fees: 550,
    address: { line1: "Ellis Bridge", line2: "Ahmedabad, Gujarat" },
  },

  // -------- Neurologists --------
  {
    name: "Dr. Pranay Mukherjee",
    email: "pranay.mukherjee@mediconnect.in",
    password: "Doctor@123",
    image: "doc8.jpg",
    speciality: "Neurologist",
    degree: "MBBS, DM (Neurology)",
    experience: "11 Years",
    about:
      "Dr. Mukherjee treats epilepsy, stroke, and neurodegenerative disorders.",
    fees: 850,
    address: { line1: "Salt Lake", line2: "Kolkata, West Bengal" },
  },
  {
    name: "Dr. Harshit Goyal",
    email: "harshit.goyal@mediconnect.in",
    password: "Doctor@123",
    image: "doc9.jpg",
    speciality: "Neurologist",
    degree: "MBBS, DM (Neurology)",
    experience: "9 Years",
    about:
      "Dr. Goyal specializes in headache disorders, nerve pain, and movement disorders.",
    fees: 800,
    address: { line1: "Civil Lines", line2: "Ajmer, Rajasthan" },
  },

  // -------- Gastroenterologists --------
  {
    name: "Dr. Rahul Menon",
    email: "rahul.menon@mediconnect.in",
    password: "Doctor@123",
    image: "doc10.jpg",
    speciality: "Gastroenterologist",
    degree: "MBBS, DM (Gastroenterology)",
    experience: "10 Years",
    about:
      "Dr. Menon manages liver diseases, IBS, and digestive disorders with evidence-based care.",
    fees: 750,
    address: { line1: "Panampilly Nagar", line2: "Kochi, Kerala" },
  },
  {
    name: "Dr. Karan Oberoi",
    email: "karan.oberoi@mediconnect.in",
    password: "Doctor@123",
    image: "doc11.jpg",
    speciality: "Gastroenterologist",
    degree: "MBBS, DM (Gastroenterology)",
    experience: "7 Years",
    about:
      "Dr. Oberoi focuses on acid reflux, liver health, and endoscopic procedures.",
    fees: 700,
    address: { line1: "Model Town", line2: "Ludhiana, Punjab" },
  }
];

